#!/usr/bin/sh

#if public key already generated
if [ ! -e ~/.ssh/id_rsa.pub ]
then
    ssh-keygen -t rsa
fi

help () {
    echo "usage: "
    echo "    owl.sh -u username -h hostaddr(ip_addr)"
}

#process command line arguments
while getopts ":u:h:" arg; do
    case "$arg" in
        u)
            u=${OPTARG}
            ;;
        h)
            h=${OPTARG}
            ;;
        *)
	    help
	    exit 1
            ;;
    esac
done

#create remote .ssh directory if not exist
ssh ${u}@${h} mkdir -p .ssh

#append local public key to remote mechine knowhosts
cat ~/.ssh/id_rsa.pub | ssh ${u}@${h} 'cat >> .ssh/authorized_keys'
